buildscript {
    ext.kotlin_version = '1.9.22'  // Update this to the latest Kotlin version (2.1.0 or higher)
    repositories {
        google()  // 確保這裡有 google() 存儲庫
        mavenCentral()  // 確保這裡有 mavenCentral() 存儲庫
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'  // 用於 Android Gradle Plugin 的版本
        classpath 'com.google.gms:google-services:4.3.15'  // 用於 Firebase 的插件
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"  // Kotlin plugin
        // 如果需要其他依賴，您也可以在這裡添加
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'com.fasterxml.jackson.core:jackson-core:2.14.2'
            force 'ch.randelshofer:fastdoubleparser:0.7.0'
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
