name: Flutter Web Deploy

on:
  push:
    branches:
      - master  # 你的主要分支，或改成 gh-pages 看你實際用哪個分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'  # 改成 3.3.2，符合 Dart SDK ^3.6.2

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages  # 如果你是用 gh-pages 分支來發佈，這行一定要加
